//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;carteCommunaute&gt;
        ///  &lt;carte&gt;
        ///	  Avance à Go
        ///  &lt;/carte&gt;
        ///  &lt;carte&gt;
        ///	  Erreur bancaire en votre faveur - Collect 200 $
        ///  &lt;/carte&gt;
        ///  &lt;carte&gt;
        ///	  Frais de médecin - Payer 50 $
        ///  &lt;/carte&gt;
        ///  &lt;carte&gt;
        ///	  De la vente de stock vous obtenez 50 $
        ///  &lt;/carte&gt;
        ///  &lt;carte&gt;
        ///	  Sortez de prison gratuitement - Cette carte peut être conservée jusqu&apos;à ce qu&apos;elle soit nécessaire ou vendue
        ///  &lt;/carte&gt;
        ///  &lt;carte&gt;
        ///	  Aller à la prison - Aller directement à la prison - Ne pas passer Go - Ne pas recuei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string carteCommunaute {
            get {
                return ResourceManager.GetString("carteCommunaute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;carteChance&gt;
        ///  &lt;carte type=&quot;deplacement&quot; dest=&quot;INDEX_GO&quot; passerGo=&quot;true&quot;&gt;
        ///	  Avancez à Go (percevez 200 $)	
        ///  &lt;/carte&gt;
        ///  &lt;carte type=&quot;deplacement&quot; dest=&quot;INDEX_BELLEVILLE&quot; passerGo=&quot;true&quot;&gt;
        ///	  Avancez à l&apos;avenue Illinois. - Si vous passez Go, percevez 200 $
        ///  &lt;/carte&gt;
        ///  &lt;carte&gt;
        ///	  Avancez à St. Charles Place - Si vous passez Go, percevez 200 $
        ///  &lt;/carte&gt;
        ///  &lt;carte&gt;
        ///	  Avancez le jeton à l&apos;utilitaire le plus proche. Si vous êtes non propriétaire, vous pouvez l&apos;acheter aup [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cartesChances {
            get {
                return ResourceManager.GetString("cartesChances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CartesTest&gt;
        ///  &lt;carte type=&quot;deplacement&quot; passerGo=&quot;true&quot;&gt;
        ///    &lt;destinationPossible val=&quot;INDEX_GO&quot; /&gt;
        ///    Avancez à Go (percevez 200 $)
        ///  &lt;/carte&gt;
        ///  &lt;carte type=&quot;deplacement&quot; passerGo=&quot;true&quot;&gt;
        ///    &lt;destinationPossible val=&quot;INDEX_BELLEVILLE&quot; /&gt;
        ///    Avancez à l&apos;avenue Belleville. - Si vous passez Go, percevez 200 $
        ///  &lt;/carte&gt;
        ///  &lt;carte type=&quot;deplacement&quot; passerGo=&quot;true&quot;&gt;
        ///    &lt;destinationPossible val=&quot;INDEX_TRAIN_1&quot; /&gt;
        ///    &lt;destinationPossible val=&quot;INDEX_TRAIN_2&quot; /&gt;
        ///    &lt;de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CartesTest {
            get {
                return ResourceManager.GetString("CartesTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CheminFers&gt;
        ///	&lt;Titre&gt;
        ///    &lt;IndexDictionnaire&gt;INDEX_READING_RR&lt;/IndexDictionnaire&gt;
        ///		&lt;Nom&gt;Reading RR&lt;/Nom&gt;
        ///		&lt;Position&gt;5&lt;/Position&gt;
        ///		&lt;Prix&gt;200&lt;/Prix&gt;
        ///		&lt;Location&gt;
        ///      &lt;unTrain&gt;25&lt;/unTrain&gt;
        ///      &lt;deuxTrains&gt;50&lt;/deuxTrains&gt;
        ///      &lt;troisTrains&gt;75&lt;/troisTrains&gt;
        ///      &lt;quatreTrains&gt;100&lt;/quatreTrains&gt;
        ///		&lt;/Location&gt;    
        ///	&lt;/Titre&gt;
        ///	&lt;Titre&gt;
        ///    &lt;IndexDictionnaire&gt;INDEX_PENSYLVANNIA_RR&lt;/IndexDictionnaire&gt;
        ///		&lt;Nom&gt;Pennsylvania RR&lt;/Nom&gt;
        ///		&lt;Position&gt;15&lt;/Position&gt;
        ///		&lt;Prix&gt;200&lt;/Pri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cheminFer {
            get {
                return ResourceManager.GetString("cheminFer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Proprietes&gt;
        ///  
        ///	  &lt;Titre&gt;
        ///		  &lt;Nom&gt;Boulevard de Belleville&lt;/Nom&gt;
        ///      &lt;IndexDictionnaire&gt;INDEX_BELLEVILLE&lt;/IndexDictionnaire&gt;
        ///		  &lt;Position&gt;1&lt;/Position&gt;
        ///		  &lt;Prix&gt;60&lt;/Prix&gt;
        ///		  &lt;Location&gt;
        ///		    &lt;base&gt;2&lt;/base&gt;
        ///		    &lt;uneMaison&gt;10&lt;/uneMaison&gt;
        ///		    &lt;deuxMaisons&gt;30&lt;/deuxMaisons&gt;
        ///		    &lt;troisMaisons&gt;90&lt;/troisMaisons&gt;
        ///		    &lt;quatreMaisons&gt;160&lt;/quatreMaisons&gt;
        ///		    &lt;hotel&gt;250&lt;/hotel&gt;
        ///		  &lt;/Location&gt;
        ///      &lt;Couleur&gt;0&lt;/Couleur&gt;
        ///	  &lt;/Titre&gt;
        ///
        ///	  &lt;Titre&gt;
        ///		  &lt;Nom&gt;Rue Lecourbe&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string propriete {
            get {
                return ResourceManager.GetString("propriete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Service&gt;
        ///	&lt;Titre&gt;
        ///		&lt;Nom&gt;Electric Company&lt;/Nom&gt;
        ///		&lt;Position&gt;2&lt;/Position&gt;
        ///		&lt;Prix&gt;150&lt;/Prix&gt;
        ///	&lt;/Titre&gt;
        ///
        ///	&lt;Titre&gt;
        ///		&lt;Nom&gt;Water Works&lt;/Nom&gt;
        ///		&lt;Position&gt;2&lt;/Position&gt;
        ///		&lt;Prix&gt;150&lt;/Prix&gt;
        ///	&lt;/Titre&gt;
        ///&lt;/Service&gt;.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
    }
}
